# Data Cleaning

## Import relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load Interim Data

In [2]:
train_df = pd.read_csv("../data/interim/train_window.csv", parse_dates=["InvoiceDate"])
validation_df = pd.read_csv("../data/interim/validation_window.csv")

print("Train shape:", train_df.shape)
print("Validation shape:", validation_df.shape)

Train shape: (502938, 8)
Validation shape: (516384, 8)

In [3]:
train_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,1/12/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,1/12/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,1/12/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,1/12/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,1/12/2009 7:45,1.25,13085.0,United Kingdom

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502938 entries, 0 to 502937
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      502938 non-null  object
 1   StockCode    502938 non-null  object
 2   Description  500117 non-null  object
 3   Quantity     502938 non-null  int64
 4   InvoiceDate  502938 non-null  object
 5   Price        502938 non-null  float64
 6   Customer ID  402731 non-null  float64
 7   Country      502938 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 30.7+ MB

In [5]:
validation_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
validation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 516384 entries, 0 to 516383
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      516384 non-null  object
 1   StockCode    516384 non-null  object
 2   Description  514945 non-null  object
 3   Quantity     516384 non-null  int64
 4   InvoiceDate  516384 non-null  object
 5   Price        516384 non-null  float64
 6   Customer ID  389168 non-null  float64
 7   Country      516384 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 31.5+ MB

## Change InvoiceData data type

In [7]:
train_df["InvoiceDate"] = pd.to_datetime(
    train_df["InvoiceDate"],
    format="mixed",
    dayfirst=True
)

validation_df["InvoiceDate"] = pd.to_datetime(
    validation_df["InvoiceDate"],
    format="mixed",
    dayfirst=True
)

In [8]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502938 entries, 0 to 502937
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      502938 non-null  object
 1   StockCode    502938 non-null  object
 2   Description  500117 non-null  object
 3   Quantity     502938 non-null  int64
 4   InvoiceDate  502938 non-null  datetime64[ns]
 5   Price        502938 non-null  float64
 6   Customer ID  402731 non-null  float64
 7   Country      502938 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 30.7+ MB

In [9]:
validation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 516384 entries, 0 to 516383
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      516384 non-null  object
 1   StockCode    516384 non-null  object
 2   Description  514945 non-null  object
 3   Quantity     516384 non-null  int64
 4   InvoiceDate  516384 non-null  datetime64[ns]
 5   Price        516384 non-null  float64
 6   Customer ID  389168 non-null  float64
 7   Country      516384 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 31.5+ MB

### Strip Column Names

In [10]:
train_df.columns = train_df.columns.str.strip()
validation_df.columns = validation_df.columns.str.strip()

## Remove Duplicate Rows

In [11]:
train_df = train_df.drop_duplicates()
validation_df = validation_df.drop_duplicates()

## Remove Cancelled Invoices

In [12]:
train_df = train_df[~train_df["Invoice"].astype(str).str.startswith("C")]
validation_df = validation_df[~validation_df["Invoice"].astype(str).str.startswith("C")]

## Remove Invalid Quantity & Price

In [13]:
train_df = train_df[(train_df["Quantity"] > 0) & (train_df["Price"] > 0)]
validation_df = validation_df[(validation_df["Quantity"] > 0) & (validation_df["Price"] > 0)]

## Remove Missing Customer ID

In [14]:
train_df = train_df.dropna(subset=["Customer ID"])
validation_df = validation_df.dropna(subset=["Customer ID"])

## Convert Customer ID to String

In [15]:
train_df["Customer ID"] = train_df["Customer ID"].astype(int).astype(str)
validation_df["Customer ID"] = validation_df["Customer ID"].astype(int).astype(str)

## Create TotalPrice Feature

In [16]:
train_df["TotalPrice"] = train_df["Quantity"] * train_df["Price"]
validation_df["TotalPrice"] = validation_df["Quantity"] * validation_df["Price"]

In [17]:
train_df.info()
train_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 386732 entries, 0 to 502937
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      386732 non-null  object
 1   StockCode    386732 non-null  object
 2   Description  386732 non-null  object
 3   Quantity     386732 non-null  int64
 4   InvoiceDate  386732 non-null  datetime64[ns]
 5   Price        386732 non-null  float64
 6   Customer ID  386732 non-null  object
 7   Country      386732 non-null  object
 8   TotalPrice   386732 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 29.5+ MB

,Quantity,InvoiceDate,Price,TotalPrice
count,386732.000000,386732,386732.000000,386732.000000
mean,13.864767,2010-06-25 10:26:44.881158144,3.312451,21.946923
min,1.000000,2009-12-01 07:45:00,0.001000,0.001000
25%,2.000000,2010-03-23 14:09:00,1.250000,5.000000
50%,5.000000,2010-07-01 14:29:00,1.950000,12.500000
75%,12.000000,2010-10-07 16:48:00,3.750000,19.500000
max,19152.000000,2010-11-30 19:35:00,10953.500000,15818.400000
std,98.973734,NaN,35.673268,77.259489

## Reset Index

In [25]:
train_df = train_df.reset_index(drop=True)
validation_df = validation_df.reset_index(drop=True)

## Save Cleaned Datasets

In [26]:
train_df.to_csv("../data/processed/train_clean.csv", index=False)
validation_df.to_csv("../data/processed/validation_clean.csv", index=False)

## Final Summary – Data Cleaning Completed

In this notebook, I prepared the interim datasets for feature engineering and segmentation analysis.

The goal of this stage was to ensure that only valid and meaningful transactional data is used for RFM calculation.

### Cleaning steps performed:

- Removed duplicate records

- Removed cancelled invoices (Invoice numbers starting with "C")

- Removed transactions with non-positive Quantity or Price

- Removed records with missing Customer ID

- Customer ID from float to string to correctly represent it as an identifier

- Parsed InvoiceDate as datetime format

- Created a new feature: TotalPrice = Quantity × Price

After applying these steps, the datasets now contain only valid purchase transactions linked to identifiable customers.

Output files saved:

- train_clean.csv

- validation_clean.csv

The cleaned datasets are stored in the processed folder and are now ready for RFM feature engineering in the next notebook.